# Stage: Install and cache dependencies
FROM --platform=linux/amd64 oven/bun:1.2.2-alpine
LABEL author=gab-cat

WORKDIR /app

# Copy package files and install dependencies
COPY bun.lock package.json ./ 
COPY prisma ./prisma
RUN bun add .
