# Stage: Install and cache dependencies
FROM --platform=linux/amd64 node:18.20.4-alpine3.20 AS client-cache
LABEL author=gab-cat

WORKDIR /client-cache

# Install pnpm
RUN npm install -g pnpm@9.15.2

# Copy package files and install dependencies
COPY pnpm-lock.yaml package.json ./
RUN pnpm install
