name: 2. CACHE - Build & Push

on:
  workflow_dispatch: 

jobs:
  client-build-and-push:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    environment: Cache
    permissions:
      contents: write
      pull-requests: write
      checks: write
    env:
      ENVIRONMENT: Cache
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Check if actor is repository owner
        run: |
          if [ "${{ github.actor }}" != "${{ github.repository_owner }}" ]; then
            echo "This workflow can only be run by the repository owner."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ env.DOCKER_USERNAME }} 
          password: ${{ env.DOCKER_PASSWORD }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build cache image and push to Docker Hub
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: .
          file: ./Dockerfile.cache
          tags: gabcat/merchtrack:cache
          cache-from: type=registry,ref=gabcat/merchtrack:cache
          cache-to: type=registry,ref=gabcat/merchtrack:cache, mode=max
          push: true
